apiVersion: v1
kind: Service
metadata:
  labels:
    app: random_forest_classifier
    version: v1
  name: random-forest-classifier-v1
  namespace: mlops
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: random_forest_classifier
    version: v1
  type: ClusterIP
